[tool.pytest.ini_options]
testpaths = ["electrum_command_center/tests"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.mypy]
python_version = "3.11"
strict_optional = false
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true

[tool.pyright]
pythonVersion = "3.11"
include = ["electrum_command_center"]
